mixin:
proxy-groups:
  - name: '🎮 游戏平台'
    type: select
    proxies:
      - '🎯 全球直连'
      - '上海电信转台湾BGP[M][Trojan][倍率:1]'
      - '上海电信转台湾BGP2[M][Trojan][倍率:1]'
      - '台湾HiNet[M][Trojan][测试][倍率:0.5]'
      - '台湾HiNet2[M][Trojan][测试][倍率:0.5]'
      - '安徽联通转台湾HiNet[M][Trojan][C][倍率:1]'
      - '安徽联通转台湾HiNet2[Trojan][C][倍率:1]'
      - '安徽联通转台湾KBT[M][Trojan][C][倍率:1]'
      - '上海联通转德国DF[Trojan][C][倍率:0.8]'
      - '安徽联通转德国HA[M][Trojan][C][倍率:0.9]'
      - '安徽联通转德国HZ[Trojan][C][倍率:0.8]'
      - '安徽联通转德国HZ2[Trojan][C][倍率:0.8]'
      - '德国DF[M][Trojan][倍率:0.5]'
      - '上海联通转新加坡BGP[M][Trojan][C][倍率:0.8]'
      - '上海联通转新加坡BGP3[M][Trojan][C][倍率:0.9]'
      - '上海联通转新加坡BGP4[M][Trojan][C][倍率:0.9]'
      - '上海联通转新加坡BGP5[M][Trojan][C][倍率:0.8]'
      - '上海联通转新加坡BGP7[M][Trojan][C][倍率:0.8]'
      - '安徽联通转新加坡BGP2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转新加坡BGP3[M][Trojan][C][倍率:0.9]'
      - '安徽联通转新加坡BGP4[M][Trojan][C][倍率:0.9]'
      - '新加坡BGP[M][Trojan][倍率:0.7]'
      - '上海电信转日本NTT[M][Trojan][倍率:1]'
      - '上海电信转日本NTT2[M][Trojan][倍率:1]'
      - '上海电信转日本NTT3[M][Trojan][倍率:1]'
      - '上海电信转日本NTT4[M][Trojan][倍率:1]'
      - '上海电信转日本NTT5[M][Trojan][倍率:1]'
      - '上海电信转日本NTT6[M][Trojan][倍率:1]'
      - '上海电信转日本NTT7[M][Trojan][倍率:1]'
      - '上海联通转日本BGP[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本BGP2[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本BGP3[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本BGP4[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本BGP5[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本BGP6[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT[Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT2[Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT3[Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT7[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT8[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT9[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT10[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT11[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT12[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT13[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本NTT14[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本TE[M][Trojan][C][倍率:0.8]'
      - '上海联通转日本TE3[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本BGP[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本BGP2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本BGP3[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT[Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT2[Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT4[Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT5[Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT6[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT8[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT9[Trojan][C][倍率:0.8]'
      - '安徽联通转日本NTT11[Trojan][C][倍率:0.8]'
      - '安徽联通转日本TE[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本TE2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本TE3[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本TE4[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本TE5[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本Webarena[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本Webarena2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转日本Webarena3[M][Trojan][C][倍率:0.9]'
      - '日本BGP2[M][Trojan][测试][倍率:0.6]'
      - '日本NTT[M][Trojan][测试][倍率:0.3]'
      - '日本NTT2[M][Trojan][测试][倍率:0.3]'
      - '安徽联通转法国SN[Trojan][C][倍率:0.8]'
      - '深港专线[VLESS][倍率:2.5]'
      - '深港专线2[VLESS][倍率:2.5]'
      - '深港专线3[VLESS][倍率:2.5]'
      - '深港专线5[VLESS][倍率:2.5]'
      - '深港专线6[VLESS][倍率:2.5]'
      - '深港专线7[VLESS][倍率:2.5]'
      - '深港专线8[VLESS][倍率:2.5]'
      - '深港专线9[M][AnyTLS][C][倍率:2.5]'
      - '深港专线10[M][AnyTLS][C][倍率:2.5]'
      - '深港专线11[M][AnyTLS][C][倍率:2.5]'
      - '深港专线12[M][AnyTLS][C][倍率:2.5]'
      - '深港专线13[M][AnyTLS][C][倍率:2.5]'
      - '深港专线15[M][AnyTLS][C][倍率:2.5]'
      - '上海电信转美国AN[M][Trojan][倍率:1]'
      - '上海电信转美国GS[Trojan][倍率:1]'
      - '上海电信转美国GS2[Trojan][倍率:1]'
      - '上海电信转美国GS3[Trojan][倍率:1]'
      - '上海电信转美国GS4[Trojan][倍率:1]'
      - '上海电信转美国GS5[Trojan][倍率:1]'
      - '上海电信转美国GS6[Trojan][倍率:1]'
      - '上海电信转美国GS7[Trojan][倍率:1]'
      - '上海联通转美国AN[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN3[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN5[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN6[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN7[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN8[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AN9[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国AWS[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国Cera[Trojan][C][倍率:0.9]'
      - '上海联通转美国Cera2[Trojan][C][倍率:0.9]'
      - '上海联通转美国Cera3[Trojan][C][倍率:0.9]'
      - '上海联通转美国Cera4[Trojan][C][倍率:0.9]'
      - '上海联通转美国Cera5[Trojan][C][倍率:0.9]'
      - '上海联通转美国Cera6[Trojan][C][倍率:0.9]'
      - '上海联通转美国DP[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国DP2[M][Trojan][C][倍率:0.8]'
      - '上海联通转美国FS[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国AN2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国AN4[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国AN6[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国AN7[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国Cera[Trojan][C][倍率:0.9]'
      - '安徽联通转美国Cera2[Trojan][C][倍率:0.9]'
      - '安徽联通转美国Cera3[Trojan][C][倍率:0.9]'
      - '安徽联通转美国Cera4[Trojan][C][倍率:0.9]'
      - '安徽联通转美国DP[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国DP2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国DP3[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国DP4[M][Trojan][C][倍率:0.8]'
      - '安徽联通转美国TE[M][Trojan][C][倍率:0.8]'
      - '深港专线转美国AN[M][VLESS][倍率:2.5]'
      - '美国AN[M][Trojan][测试][倍率:0.5]'
      - '美国AN2[M][Trojan][倍率:0.8]'
      - '美国BGP[M][Trojan][倍率:0.6]'
      - '美国BGP2[M][Trojan][倍率:0.6]'
      - '美国BGP3[M][Trojan][倍率:0.6]'
      - '美国BGP5[M][Mieru][测试][倍率:0.6]'
      - '美国BGP6[M][Trojan][倍率:0.6]'
      - '美国BGP7[M][Trojan][倍率:0.6]'
      - '美国BGP8[M][Trojan][倍率:0.6]'
      - '上海电信转英国CV[Trojan][倍率:1]'
      - '上海联通转英国CV[Trojan][C][倍率:0.9]'
      - '上海联通转英国CV2[Trojan][C][倍率:0.9]'
      - '英国CV[Trojan][测试][倍率:0.5]'
      - '上海电信转韩国KT[M][Trojan][倍率:1]'
      - '上海联通转韩国KT[M][Trojan][C][倍率:0.9]'
      - '上海联通转韩国SK[M][Trojan][C][倍率:0.9]'
      - '韩国KT[M][Trojan][倍率:0.5]'
      - '韩国SK[M][Trojan][倍率:0.6]'
      - '上海电信转香港BGP[M][Trojan][倍率:1]'
      - '上海电信转香港HKC[M][Trojan][倍率:1]'
      - '上海电信转香港HKC2[M][Trojan][倍率:1]'
      - '上海电信转香港HKC3[M][Trojan][倍率:1]'
      - '上海电信转香港HKC4[M][Trojan][倍率:1]'
      - '上海电信转香港HKC5[M][Trojan][倍率:1]'
      - '上海电信转香港HKC6[M][Trojan][倍率:1]'
      - '上海电信转香港HKT[M][Trojan][倍率:1]'
      - '上海联通转香港HKC[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKC3[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKC4[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKT[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKT3[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKT4[M][Trojan][C][倍率:0.8]'
      - '上海联通转香港HKT5[M][Trojan][C][倍率:0.8]'
      - '安徽联通转香港BGP[M][Trojan][C][倍率:0.9]'
      - '安徽联通转香港BGP4[M][Trojan][C][倍率:0.9]'
      - '安徽联通转香港BGP5[M][Trojan][C][倍率:0.9]'
      - '安徽联通转香港HKT2[M][Trojan][C][倍率:0.8]'
      - '安徽联通转香港HKT3[M][Trojan][C][倍率:0.9]'
      - '深港专线转香港BGP3[M][VLESS][倍率:2.5]'
      - '深港专线转香港BGP4[M][VLESS][倍率:2.5]'
      - '深港专线转香港BGP7[M][VLESS][倍率:2.5]'
      - '深港专线转香港BGP8[M][VLESS][倍率:2.5]'
      - '深港专线转香港HGC商宽4[VLESS][倍率:2.5]'
      - '香港BGP[M][Trojan][倍率:0.3]'
      - '香港BGP2[M][Trojan][倍率:0.8]'
      - '香港HKT[M][Trojan][倍率:0.5]'

rules:
    - 'DOMAIN-SUFFIX,epicgames.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,helpshift.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,paragon.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,unrealengine.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,playstation.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,playstation.net,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,playstationnetwork.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,sony.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,sonyentertainmentnetwork.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,fanatical.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,humblebundle.com,🎮 游戏平台'
    - 'DOMAIN,steambroadcast.akamaized.net,🎮 游戏平台'
    - 'DOMAIN,steamcdn-a.akamaihd.net,🎮 游戏平台'
    - 'DOMAIN,steamcommunity-a.akamaihd.net,🎮 游戏平台'
    - 'DOMAIN,steampipe.akamaized.net,🎮 游戏平台'
    - 'DOMAIN,steamstore-a.akamaihd.net,🎮 游戏平台'
    - 'DOMAIN,steamusercontent-a.akamaihd.net,🎮 游戏平台'
    - 'DOMAIN,steamuserimages-a.akamaihd.net,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,fanatical.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,humblebundle.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,playartifact.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steamgames.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steamstat.us,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,underlords.com,🎮 游戏平台'
    - 'DOMAIN-SUFFIX,valvesoftware.com,🎮 游戏平台'
